/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_bigboydave_common_security_AkSecurity */

#ifndef _Included_cn_bigboydave_common_security_AkSecurity
#define _Included_cn_bigboydave_common_security_AkSecurity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_bigboydave_common_security_AkSecurity
 * Method:    encrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_bigboydave_common_core_security_AkSecurity_encrypt
  (JNIEnv *env, jobject obj, jstring value);

/*
 * Class:     cn_bigboydave_common_security_AkSecurity
 * Method:    decrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_bigboydave_common_core_security_AkSecurity_decrypt
  (JNIEnv *env, jobject obj, jstring key);

#ifdef __cplusplus
}
#endif
#endif
